/* {{AUTH_IMPORTS}} */
import './globals.css';

export const metadata = {
  title: 'StuckonStack App',
  description: 'Generated by create-stuckonstack',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    /* {{AUTH_PROVIDER_START}} */
    <html lang="en">
      <body>{children}</body>
    </html>
    /* {{AUTH_PROVIDER_END}} */
  );
}
